#!/bin/bash
echo "this will define the order that the packages should be installed in"
echo "MAKE SURE THAT WGET IS INSTALLED \n \n"
echo "\n1)     3.10-Random"
echo "\n2)     4.19openSSL"
echo "\n1)     4.2-CertificateAuth"
echo "\n1)     4.26-Sudo (one of my favorites! :)"
echo "NOTE: I need to install the dep of open ssh so it can come here!"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
