#!/bin/bash
echo "this will define the order that the packages should be installed in"
echo "MAKE SURE THAT WGET IS INSTALLED \n \n"
echo "\n1)     3.10-Random"
echo "\n2)     4.19openSSL"
echo "\n3)     4.2-CertificateAuth"
echo "\n4)     4.26-Sudo (one of my favorites! :)"
echo "NOTE: I need to install the dep of open ssh so it can come here!"
echo "\n5)     5.5-LVM2"
echo "\n6)     5.10-parted" # ZOTE::: start with next nextime
echo "\n7)     libffi"
echo "\n8)     python2"
echo "\n9)     GLib"
echo "\n10)     freetype-2"
echo "\n11)     fontconfig-2"
echo "\n12)     Xorg-7"
echo "\n13)     util-macros-1.19.0"
echo "\n14)     Xorg Protocol Headers"
echo "\n15)     libXau"
echo "\n16)     xcb-proto"
echo "\n17)     libxcb" #start with next on sunday, start with xorg librarys ps. have fun (its a short one) :)
echo "\n18)     xorg librarys"
echo "\n19)     dbus"
echo "\n21)     at-spi2-core"
echo "\n22)     atk"
echo "\n23)     at-spi2-atk"
echo "\n24)     NASM"
echo "\n25)     yasm" #later on monday or on tuesday or whenever i get back to this work on libjpeg-turbo-1.5.1. I also LOVE how many fricken dependancys gdk has! :)
echo "\n26)     "
echo "\n27)     "
echo "\n28)     "
echo "\n29)     "
echo "\n30)     "
echo "\n31)     "
echo "\n32)     "
