#!/bin/bash
echo "this will define the order that the packages should be installed in"
echo "MAKE SURE THAT WGET IS INSTALLED \n \n"
echo "\n1)     3.10-Random"
echo "\n2)     4.19openSSL"
echo "\n1)     4.2-CertificateAuth"
echo "\n1)     4.26-Sudo (one of my favorites! :)"
echo "NOTE: I need to install the dep of open ssh so it can come here!"
echo "\n1)     5.5-LVM2"
echo "\n1)     5.10-parted" # ZOTE::: start with next nextime
echo "\n1)     libffi"
echo "\n1)     python2"
echo "\n1)     GLib"
echo "\n1)     freetype-2"
echo "\n1)     fontconfig-2"
echo "\n1)     Xorg-7"
echo "\n1)     util-macros-1.19.0"
echo "\n1)     Xorg Protocol Headers"
echo "\n1)     libXau"
echo "\n1)     xcb-proto"
echo "\n1)     libxcb"
echo "\n1)     4.19openSSL"
echo "\n1)     4.19openSSL"
